name: thunderscout2
description: "Thunder Scout 2.0 made with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  mockito: ^5.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.10.0  # Icon generation package

  http: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Define assets here if any images are added later
  assets:
    - assets/icon/icon.png
    - assets/config.json
    - assets/thunderscout_logo.png

# Configuration for flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"  # Path to the app icon
